### ISSUE TITLE
issue on JDBCDBImporter.getForeignSchemas using metaData.getImportedKeys to get schemas

### ISSUE THREAD

**Issue by ccyoong676** [rapiddweller/rd-lib-jdbacl#13]
not sure why JDBCDBImporter.getForeignSchemas is using metaData.getImportedKeys to get schemas, by using null as table name in getImportedKeys method will cause error or might not works as expected in some database.
![image](https://user-images.githubusercontent.com/37040176/118928920-711df400-b976-11eb-94a7-e26ea76eef50.png)

MySql driver will hit validation and throw error
![image](https://user-images.githubusercontent.com/37040176/118929460-22bd2500-b977-11eb-8b2c-efbd1a7a1c4e.png)

**Comment by ake2l** [comment]
i am going to check this

**Comment by ake2l** [comment]
I remember, the metadata import is always driver specific, so in these cases i handle import for Ms SQL server and H2 different  because these are different because of driver funktionality.

**Comment by ake2l** [comment]
And i am using get imported keys here to get a list of schemas with foreignkey references to use this list as base to import metadata for these related schemas as well, this approach works pretty good with postgres , ms sql server  and h2 , i am not sure if i tested it with mysql ... but i am always open for improvements and suggestions

**Comment by ccyoong676** [comment]
if the metadata import is always driver specific, I think changing the "not equal to sql_server" to "equal to postgres" would be more appropriate, since the "not equal to sql_server" logic only applicable to postgres.

**Comment by ake2l** [comment]
oh i see, totally agree definitely needs a rework to handle all supported dialects properly

**Comment by ccyoong676** [comment]
created a pull request to update the logic as discussed, https://github.com/rapiddweller/rd-lib-jdbacl/pull/14.
